### ISSUE TITLE
Upload to specific folder

### ISSUE THREAD

**Issue by mruknowme** [bacongobbler/azure-blob-storage-upload#12]
Is it possible to upload to a specific folder on the blob and clean the folder before upload?

Thanks

**Comment by bacongobbler** [comment]
You can provide the —destination flag as part of the `extra_flags` field. Enabling the `sync` flag will purge the entire container. Let me know what you come up with.

**Comment by mruknowme** [comment]
Perfect, thanks, will try in a moment and let you know here :)

**Comment by mruknowme** [comment]
@bacongobbler sorry if it's a dumb question.. I added this line to my yml file `extra_flags: --destination-path test` but after completing the job it still seem to upload to root directory.

According to guide, from what I understand, just specifying folder name should work:
https://docs.microsoft.com/en-us/cli/azure/ext/storage-preview/storage/blob/directory?view=azure-cli-latest

Do you know what could be the issue?

Thanks

**Comment by bacongobbler** [comment]
Can you share an example or a link to your workflow YAML?

**Comment by mruknowme** [comment]
```yml
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npm run build
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'dist'
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionString }}
          sync: true
          extra_flags: --destination-path test
```
