### ISSUE TITLE
Task fails with "ERROR: unrecognized arguments" when using extra_data

### ISSUE THREAD

**Issue by LadyCailin** [bacongobbler/azure-blob-storage-upload#15]
Full error message: 
`ERROR: unrecognized arguments: --pattern commandhelper*-full.jar --destination-path build-20`
in for example this run: https://github.com/EngineHub/CommandHelper/actions/runs/894114850. I've tried a number of different configurations, but I'm not sure what's going on here. Current configuration is here: https://github.com/EngineHub/CommandHelper/blob/9a5489da87331d80def17827b510e510056be0bb/.github/workflows/maven-publish.yml

```
name: Upload to Blob Store      
uses: bacongobbler/azure-blob-storage-upload@v1.2.0
      with:
        source_dir: target
        container_name: builds
        connection_string: ${{ secrets.BlobStoreConnectionString }} 
        extra_args: --pattern commandhelper*-full.jar --destination-path build-${{ github.RUN_NUMBER }}
```

I'm not sure if this is a problem with az or the task, but I tried running az directly on my local machine with this parameter set, and it seems to have worked, but I'm not sure how to debug further. Any help would be appreciated!
