### ISSUE TITLE
ERROR: incorrect usage: source must be an existing directory in CI

### ISSUE THREAD

**Issue by Ibrahim-CloudLabs** [bacongobbler/azure-blob-storage-upload#20]
The source directory is not detected when I build my source folder (dist) using Github actions. The targeted source directory gets created after my first job (Build on Windows) runs. It does find the source when I run (Build on Windows, creates a dist folder in ./solutions/app/) locally and upload it to repo. 

```
name: Build Artifcats and Upload To Azure Blob Storage
on:
  push:
    branches:
      - main

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14.2.0
Running Scripts**......... 

  upload:
    runs-on: ubuntu-latest
    needs: build_on_win   (Notice here I'm waiting for the artifacts to be built)
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: ./solutions/app/dist
          container_name: 'app/latest'
          connection_string: .......
          sync: true
```
