### ISSUE TITLE
Action returns ErrorCode:BlobAlreadyExists

### ISSUE THREAD

**Issue by bacongobbler** [bacongobbler/azure-blob-storage-upload#21]
A recent bug was introduced to the Azure CLI preventing `az storage blob upload-batch` to overwrite existing objects. Prior versions of the Azure CLI does not prevent this from happening.

At this time, there is no workaround short of deleting the object before uploading - see https://github.com/Azure/azure-cli/issues/21477.

At this time I'm inclined to wait and see if a patch will be released upstream, though I'm prepared to [pin to a specific version](https://github.com/bacongobbler/azure-blob-storage-upload/blob/87697ee966ddc99fe69000ba8d8a2483d12b6928/Dockerfile#L1) if a fix is delayed for a period of time.

**Comment by bacongobbler** [comment]
Should be fixed with https://github.com/bacongobbler/azure-blob-storage-upload/commit/063a68b3405530f0e6d584cc8c9732922dcee34f - will continue to monitor the upstream issue.

**Comment by rwest202** [comment]
Can a new release be made with this change?

**Comment by bacongobbler** [comment]
I’m holding off pending a fix upstream. It’s been less than 24 hours since the latest version of azure-cli was released.

For now use `bacongobbler/azure-blob-storage-upload@main` in your workflow to receive the fix.

**Comment by bacongobbler** [comment]
It appears this is a breaking change to the azure cli. As of 2.34.0, clients must now provide `--overwrite true` to allow `upload-batch` to overwrite existing objects. I agree this is a good practice, however this a breaking change in a minor version... Hooray for failing to follow semantic versioning practices? 🤷🏼

Once azure-cli 2.34.1 is released, here's an updated example with the `--overwrite` flag as shown in the README:

```
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: _dist
          container_name: www
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.tar.gz --overwrite true'
          sync: false
```

Notice that I added `--overwrite true` in the `extra_args` field.

I'll try to come up with some changes to help work around these issues in the future. I'll share more updates as things progress.

**Comment by bacongobbler** [comment]
Okay. I made a few recent changes to accommodate these issues. Here are a few solutions available to y'all.

Option 1: use `bacongobbler/azure-blob-storage-upload@main`, specifying the `overwrite` flag:

```
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: _dist
          container_name: www
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.tar.gz'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
```

Option 2: use `bacongobbler/azure-blob-storage-upload@main`, specifying the `cli_version` flag (reverting/pinning to an older version of the azure CLI):

```
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          cli_version: 2.33.0
          source_dir: _dist
          container_name: www
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.tar.gz'
```

I'll be cutting v1.3.0 soon once I verify everything's working as expected.
