### ISSUE TITLE
ERROR: unrecognized arguments: --overwrite true

### ISSUE THREAD

**Issue by everspader** [bacongobbler/azure-blob-storage-upload#24]
Hi, I had to upgrade the action to version 2.0.0 because it wasn't able to overwrite the existing file in blob storage. Now, that I explicitly set the overwrite to `true`, the `az cli` seems to not be recognizing the extra argument. Do you know what could be the issue?

```yaml
- name: Upload to Azure Storage
  uses: bacongobbler/azure-blob-storage-upload@v2.0.0
  with:
    source_dir: './dist'
    container_name: 'bundles'
    connection_string: ${{ secrets.AZURE_STORAGE_CONNECTIONSTRING }}
    sync: true
    overwrite: 'true'
```
This is the output from the actions log:
```
...
Run bacongobbler/azure-blob-storage-upload@v[2](https://github.com/.../runs/5588678713?check_suite_focus=true#step:5:2).0.0
  with:
    source_dir: ./dist
    container_name: bundles
    connection_string: ***
    sync: true
    overwrite: true

...

ERROR: unrecognized arguments: --overwrite true
...
```
