### ISSUE TITLE
`[]` response with no errors (and no file uploaded)

### ISSUE THREAD

**Issue by tommed** [bacongobbler/azure-blob-storage-upload#26]
I believe I have completed the necessary fields to utilise this action, (sensitive data redacted)

```yaml
# ...
      - run: zip -r /tmp/codagami-webhook-latest.zip *
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: /tmp
          account_name: OUR_STORAGE_ACCOUNT_NAME
          container_name: OUR_CONTAINER_NAME
          sas_token: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
          extra_args: '--pattern *.zip'
          overwrite: 'true'
```

However, the file(s) aren't being uploaded.
Scrolling to the bottom of the log I can see the status:

```
Notice:  A new release of pip available: 22.2.1 -> 22.2.2
Notice:  To update, run: pip install --upgrade pip

[]
```

So it doesn't appear to be doing anything?
