### ISSUE TITLE
Unrecognized arguments when pattern matching 

### ISSUE THREAD

**Issue by adam-bentley** [bacongobbler/azure-blob-storage-upload#31]
When I try to use pattern matching, I get an error the command is not supported
> ERROR: unrecognized arguments: <filename>.sql

```
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          sas_token: ${{ secrets.SASToken }}
          account_name : "spacestationdatabase"
          container_name: "spacestation-database"
          source_dir: "."
          overwrite: 'true'
          extra_args: '--pattern *.sql'
```

I've looked at these:
https://github.com/bacongobbler/azure-blob-storage-upload/issues/24
https://github.com/bacongobbler/azure-blob-storage-upload/issues/15

But they don't seem to provide any insight.

Thanks for the help.
