### ISSUE TITLE
ERROR: Connection error while attempting to download azcopy 10.13.0

### ISSUE THREAD

**Issue by JinIgarashi** [bacongobbler/azure-blob-storage-upload#39]
I encountered an error of `ERROR: Connection error while attempting to download azcopy 10.1` for this action.

I thought this was caused by using `main`, then I changed to use the latest tag of v3.0.0 and the error is still present. Do you know why this is happening? Looks like `azcopy` is missing...

Code for GitHub action

```yaml
      - name: deploy storybook to Blob container
        if: ${{ (github.ref == 'refs/heads/develop') }}
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          source_dir: packages/svelte-undp-design/storybook-static
          container_name: $web
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_STORYBOOK }}
          # WARNING: this will overwrite existing blobs in your blob storage
          sync: "true"
```

Log from GitHub action

```shell
Run bacongobbler/azure-blob-storage-upload@v3.0.0
  with:
    source_dir: documentation/site
    container_name: $web
    connection_string: ***
    sync: true
  env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
    ACR_ENDPOINT: ***
    ACR_USERNAME: ***
    ACR_PASSWORD: ***
/usr/bin/docker run --name b[2](https://github.com/UNDP-Data/geohub/actions/runs/12761814629/job/35569363750#step:11:2)57f276efdf96664ad480e94197849491c1_9670fd --label 52b257 --workdir /github/workspace --rm -e "CI" -e "PNPM_CACHE_FOLDER" -e "ACR_ENDPOINT" -e "ACR_USERNAME" -e "ACR_PASSWORD" -e "INPUT_SOURCE_DIR" -e "INPUT_CONTAINER_NAME" -e "INPUT_CONNECTION_STRING" -e "INPUT_SYNC" -e "INPUT_SAS_TOKEN" -e "INPUT_ACCOUNT_NAME" -e "INPUT_EXTRA_ARGS" -e "INPUT_OVERWRITE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/geohub/geohub":"/github/workspace" 52b257:f276efdf96664ad480e94197849491c1
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Positional argument '<EXTRA_OPTIONS>' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Azcopy not found, installing at /github/home/.azure/bin/azcopy
ERROR: Connection error while attempting to download azcopy 10.1[3](https://github.com/UNDP-Data/geohub/actions/runs/12761814629/job/35569363750#step:11:3).0. You could also install the specified azcopy version to /github/home/.azure/bin manually. (<urlopen error [Errno -2] Name or service not known>)
```

![image](https://github.com/user-attachments/assets/046a9fd9-4ece-4e2e-b196-8a233b1f7c41)
